# Generated by Django 3.2 on 2021-04-21 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('state', models.CharField(choices=[('alabama', 'Alabama'), ('alaska', 'Alaska'), ('arizona', 'Arizona'), ('arkansas', 'Arkansas'), ('california', 'California'), ('colorado', 'Colorado'), ('connecticut', 'Connecticut'), ('washington_dc', 'Washington D.C.'), ('delaware', 'Delaware'), ('florida', 'Florida'), ('georgia', 'Georgia'), ('hawaii', 'Hawaii'), ('idaho', 'Idaho'), ('illinois', 'Illinois'), ('indiana', 'Indiana'), ('iowa', 'Iowa'), ('kansas', 'Kansas'), ('louisiana', 'Louisiana'), ('maine', 'Maine'), ('maryland', 'Maryland'), ('massachusetts', 'Massachusetts'), ('michigan', 'Michigan'), ('minnesota', 'Minnesota'), ('mississippi', 'Mississippi'), ('missouri', 'Missouri'), ('montana', 'Montana'), ('nebraska', 'Nebraska'), ('nevada', 'Nevada'), ('new_hampshire', 'New Hampshire'), ('new_jersey', 'New Jersey'), ('new_mexico', 'New Mexico'), ('new_york', 'New York'), ('north_carolina', 'North Carolina'), ('north_dakota', 'North Dakota'), ('ohio', 'Ohio'), ('oklahoma', 'Oklahoma'), ('oregon', 'Oregon'), ('pennsylvania', 'Pennsylvania'), ('rhode_island', 'Rhode Island'), ('south_carolina', 'South Carolina'), ('south_dakota', 'South Dakota'), ('tennessee', 'Tennessee'), ('texas', 'Texas'), ('utah', 'Utah'), ('vermont', 'Vermont'), ('virginia', 'Virginia'), ('washington', 'Washington'), ('wisconsin', 'Wisconsin'), ('wyoming', 'Wyoming')], max_length=40)),
                ('city', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('route', 'Trail Route'), ('hazardous', 'Hazardous Conditions'), ('other', 'Other')], max_length=40)),
                ('content', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('alabama', 'Alabama'), ('alaska', 'Alaska'), ('arizona', 'Arizona'), ('arkansas', 'Arkansas'), ('california', 'California'), ('colorado', 'Colorado'), ('connecticut', 'Connecticut'), ('washington_dc', 'Washington D.C.'), ('delaware', 'Delaware'), ('florida', 'Florida'), ('georgia', 'Georgia'), ('hawaii', 'Hawaii'), ('idaho', 'Idaho'), ('illinois', 'Illinois'), ('indiana', 'Indiana'), ('iowa', 'Iowa'), ('kansas', 'Kansas'), ('louisiana', 'Louisiana'), ('maine', 'Maine'), ('maryland', 'Maryland'), ('massachusetts', 'Massachusetts'), ('michigan', 'Michigan'), ('minnesota', 'Minnesota'), ('mississippi', 'Mississippi'), ('missouri', 'Missouri'), ('montana', 'Montana'), ('nebraska', 'Nebraska'), ('nevada', 'Nevada'), ('new_hampshire', 'New Hampshire'), ('new_jersey', 'New Jersey'), ('new_mexico', 'New Mexico'), ('new_york', 'New York'), ('north_carolina', 'North Carolina'), ('north_dakota', 'North Dakota'), ('ohio', 'Ohio'), ('oklahoma', 'Oklahoma'), ('oregon', 'Oregon'), ('pennsylvania', 'Pennsylvania'), ('rhode_island', 'Rhode Island'), ('south_carolina', 'South Carolina'), ('south_dakota', 'South Dakota'), ('tennessee', 'Tennessee'), ('texas', 'Texas'), ('utah', 'Utah'), ('vermont', 'Vermont'), ('virginia', 'Virginia'), ('washington', 'Washington'), ('wisconsin', 'Wisconsin'), ('wyoming', 'Wyoming')], max_length=40)),
                ('intersection1', models.CharField(max_length=255)),
                ('intersection2', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cyclist.profile')),
            ],
        ),
    ]
