# Generated by Django 3.2 on 2021-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.URLField(default='http://assets.stickpng.com/images/596ce35fed07ad6118f998e8.png'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prof_pic',
            field=models.URLField(default='https://st3.depositphotos.com/4111759/13425/v/600/depositphotos_134255626-stock-illustration-avatar-male-profile-gray-person.jpg'),
        ),
    ]
