# Generated by Django 3.2 on 2021-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclist', '0002_alter_post_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=41.8789, max_digits=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=87.6359, max_digits=15),
        ),
    ]
