# Generated by Django 3.2 on 2021-04-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyclist', '0003_auto_20210427_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Route', 'Trail Route'), ('Hazardous', 'Hazardous Conditions'), ('Other', 'Other')], max_length=40),
        ),
    ]
